HOST: https://api.nearlyfreespeech.net/v2

--- NFS.net API V2 ---
---
This is a reference implementation and corresponding documentation for a candidate of the next version of the NearlyFreeSpeech.net API.
For the sake of simplicity, this reference will operate on a sample member.

All clients must accept and produce UTF-8 encoded JSON as specified in [RFC 4627](http://tools.ietf.org/html/rfc4627).
All clients must operate over TLS at all times.
All request body names must be in lowercase.
Monetary values are to be expressed in cents.
Data values are to be expressed in bytes.
Time values are to be expressed in epoch seconds.

Member-Related and Site-Related option values:
<table>
<tr>
<td>Opt. #</td>
<td>Bandwidth Report</td>
<td>Storage Report</td>
<td>Shell</td>
<td>Site Type</td>
<td>CGI Realm</td>
<td>Rewrite Log</td>
<td>Log Rotation</td>
<td>Log Compression</td>
<td>Canonical Type</td>
</tr>
<tr>
<td>0</td>
<td>1 Week/Daily</td>
<td>1 Week</td>
<td>bash</td>
<td>Static Content</td>
<td>N/A</td>
<td>Off</td>
<td>Never</td>
<td>None</td>
<td>Off</td>
</tr>
<tr>
<td>1</td>
<td>2 Weeks/Daily</td>
<td>2 Weeks</td>
<td>csh</td>
<td>Apache 2.2, CGI Optimized</td>
<td>freebsd6</td>
<td>Low</td>
<td>Monthly</td>
<td>gzip</td>
<td>Soft</td>
</tr>
<tr>
<td>2</td>
<td>1 Month/Daily</td>
<td>1 Month</td>
<td>ksh</td>
<td>Apache 2.2, PHP 5.2 Fast, CGI</td>
<td>freebsd72</td>
<td>Medium</td>
<td>Weekly</td>
<td>bzip2</td>
<td>Hard</td>
</tr>
<tr>
<td>3</td>
<td>2 Months/Daily</td>
<td>3 Months</td>
<td>sh</td>
<td>Apache 2.2, PHP 5.3 Fast, CGI</td>
<td>2011Q4</td>
<td>High</td>
<td>Daily</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>4</td>
<td>1 Month/Weekly</td>
<td>6 Months</td>
<td>tcsh</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>5</td>
<td>3 Months/Weekly</td>
<td>1 Year</td>
<td>zsh</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>6</td>
<td>6 Months/Weekly</td>
<td>N/A</td>
<td>fish</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>7</td>
<td>1 Year/Weekly</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>8</td>
<td>6 Months/Monthly</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>9</td>
<td>1 Year/Monthly</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
</table>

Domain-Related option values:
<table>
<tr>
<td>Opt. #</td>
<td>TLD</td>
<td>Registration Action</td>
<td>Renewal Action</td>
</tr>
<tr>
<td>0</td>
<td>.com</td>
<td>Register</td>
<td>None</td>
</tr>
<tr>
<td>1</td>
<td>.org</td>
<td>Transfer</td>
<td>Manual</td>
</tr>
<tr>
<td>2</td>
<td>.net</td>
<td>Renew</td>
<td>Automatic</td>
</tr>
<td>3</td>
<td>.info</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<td>4</td>
<td>.name</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<td>5</td>
<td>.biz</td>
<td>N/A</td>
<td>N/A</td>
</tr>
</table>
---

--
Member Endpoints
This section relates to all endpoints in regard to the member profile
--
Initiate registration for a new member
POST /member
> Content-Type: application/json
{
	"login": "sample",
	"name": "Sample User",
	"email": "sample@sample.com",
	"reason": "I heard this was the best webhost on the internet :)",
	"auth": "0102030405060708"
}
< 202
< Content-Type: application/json
{
	"message": "A confirmation email has been sent to complete registration."
}

Get full information about a membership and affiliated accounts, sites, domains and databases
GET /member
< 200
< Content-Type: application/json
{
	"login": "sample",
	"name": "Sample User",
	"email": "sample@sampledoma.in",
	"status": "OK",
	"supportPoints": 10,
	"globalSSH": true,
	"globalFTP": false,
	"shell": 1,
	"sessions": [
		{"start": 1344189552, "duration": 3600, "address": "127.0.0.1", "agent": "Mozilla/5.0 AppleWebKit/535.19 Ubuntu/12.04 Chrome/18.0.1025.168"}
		],
	"keys": [
		{"type": "RSA", "length": 4096, "fingerprint": "01:02:03:04:05:06:07:08:09:0A:0B:0C:0D:0E:0F:10", "comment": "Website Key (sample@sampledoma.in)", "options": ""}
		],
	"accounts": [
		{"sname": "business",
		"number": "AD20-8675309",
		"status": "OK",
		"xferTotal": 237060719903,
		"warnings": [500,100],
		"balance": 1420,
		"xferRate": 16242304,
		"xferUnbilled": 22597911,
		"storageUnbilled": 18967354,
		"created": 1041480306,
		"charged": 1344180247,
		"modified": 1344180247,
		"contact": {
			"oname": "Sample Corp",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave",
			"city": "Washington, D.C.",
			"state": "",
			"postal": 20204,
			"country": "US",
			"phone": "2027737433",
			"emergency": "sample@sample.com"
			},
		"activity": {
			"current": [
				{"name": "samplesite Site Charge", "charge": 1, "note": ""},
				{"name": "sampledb MySQL Charge", "charge": 2, "note": ""},
				{"name": "Storage Charge", "charge": 30, "note": ""}
				],
			"recurring": [
				{"name": "Dynamic Sites", "charge": 1, "note": "1 site"},
				{"name": "DNS", "charge": 0.111, "note": "1 zone, 1 registered & hosted"},
				{"name": "MySQL", "charge": 2, "note": "1 process"},
				{"name": "RespectMyPrivacy", "charge": 0, "note": "1 private domain, 1 prepaid"}
				]
			}
		},
		{"sname": "personal",
		"number": "0541-CA1CBADD",
		"status": "OK",
		"xferTotal": 23697482056,
		"warnings": [500,100],
		"balance": 719,
		"xferRate": 13729026,
		"xferUnbilled": 22597911,
		"storageUnbilled": 18967354,
		"created": 1144198923,
		"charged": 1344564246,
		"modified": 1344564246,
		"contact": {
			"oname": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave",
			"city": "Washington, D.C.",
			"state": "",
			"postal": 20204,
			"country": "US",
			"phone": "2027737433",
			"emergency": "sample@samp.le"
			},
		"activity": {
			"current": [
				{"name": "samplesite2 Site Charge", "charge": 1,"note": ""},
				{"name": "samplesite3 Site Charge", "charge": 1,"note": ""},
				{"name": "Storage Charge", "charge": 30, "note": ""}
				],
			"recurring": [
				{"name": "Dynamic Sites", "charge": 2, "note": "2 sites"},
				{"name": "Email Forwarding", "charge": 3, "note": "1 site"}
				{"name": "RespectMyPrivacy", "charge": 1, "note": "1 private domain, 0 prepaid"}
				]
			}
		}],
	"sites": [
		{"sname": "samplesite",
		"username": "sample_samplesite",
		"maintenance": false,
		"adjunct": false,
		"cname": "www.sample.com",
		"ctype": 2,
		"type": 5,
		"root": "/f2/samplesite/",
		"cluster": "coh-1-225",
		"realm": 2,
		"enabled": true,
		"control": ["Allow All"],
		"admin": "nobody",
		"bank": 100,
		"account": "AD20-8675309",
		"sshHostname": "ssh.phx.nearlyfreespeech.net",
		"ftpHostname": "ftp.phx.nearlyfreespeech.net",
		"sshAccess": true,
		"ftpAccess": false,
		"alog": false,
		"elog": false,
		"rlog": 0,
		"rotation": 0,
		"compression": 0,
		"created": 1139040612,
		"xferUnbilled": 13524972,
		"storageUnbilled": 26163811,
		"repSize": 78418944,
		"lbackup": 1344197191,
		"rbackup": 1344197191,
		"totalRAU": 109.893,
		"avgRAU": 12.206,
		"addresses": ["1.2.3.4","5.6.7.8","9.10.11.12"],
		"ipv6": false,
		"bandwidth": 0,
		"adjuncts": ["member1","member2"],
		"aliases": ["www.sample.com","samplesite.nfshost.com"],
		"tasks": [
			{"tag": "permissions", "command": "chmod -R ug+rwx /home/public/blog", "user": 1, "hour": 7, "day": -1, "date": -1}
			]
		},
		{"sname": "samplesite2",
		"username": "sample_samplesite2",
		"maintenance": false,
		"adjunct": false,
		"cname": "www.examp.le",
		"ctype": 1,
		"type": 5,
		"root": "/f5/samplesite2/",
		"cluster": "coh-1-226",
		"realm": 2,
		"enabled": true,
		"control": ["Allow All"],
		"admin": "nobody",
		"bank": 52,
		"account": "0541-CA1CBADD",
		"sshHostname": "ssh.phx.nearlyfreespeech.net",
		"ftpHostname": "ftp.phx.nearlyfreespeech.net",
		"sshAccess": true,
		"ftpAccess": false,
		"alog": false,
		"elog": false,
		"rlog": 0,
		"rotation": 0,
		"compression": 0,
		"created": 1310173385,
		"xferUnbilled": 13524972,
		"storageUnbilled": 26163811,
		"repSize": 134850810,
		"lbackup": 1344197191,
		"rbackup": 0,
		"totalRAU": 17.747,
		"avgRAU": 3.095,
		"addresses": ["13.14.15.16","17.18.19.20","21.22.23.24"],
		"ipv6": false,
		"bandwidth": 0,
		"adjuncts": [],
		"aliases": ["www.examp.le","samplesite2.nfshost.com"],
		"tasks": []
		},
		{"sname": "samplesite3",
		"username": "sample_samplesite3",
		"maintenance": false,
		"adjunct": false,
		"cname": "samplesite3.nfshost.com",
		"ctype": 0,
		"type": 5,
		"root": "/f1/samplesite3/",
		"cluster": "coh-1-227",
		"realm": 2,
		"enabled": false,
		"control": ["Allow All"],
		"admin": "nobody",
		"bank": 96,
		"account": "0541-CA1CBADD",
		"sshHostname": "ssh.phx.nearlyfreespeech.net",
		"ftpHostname": "ftp.phx.nearlyfreespeech.net",
		"sshAccess": true,
		"ftpAccess": false,
		"alog": false,
		"elog": false,
		"rlog": 0,
		"rotation": 0,
		"compression": 0,
		"created": 1310173385,
		"xferUnbilled": 13524972,
		"storageUnbilled": 26163811,
		"repSize": 78418944,
		"lbackup": 1344197191,
		"rbackup": 0,
		"totalRAU": 202.112,
		"avgRAU": 18.586,
		"addresses": ["25.26.27.28","29.30.31.32","33.34.35.36","2e80::ff09:1123"],
		"ipv6": true,
		"bandwidth": 0,
		"adjuncts": ["member1","member3"],
		"aliases": ["samplesite3.nfshost.com"],
		"tasks": [
			{"tag": "logstuff", "command": "/home/private/dologstuff", "hour": 3, "day": -1, "date": 31},
			{"tag": "optimizedb", "command": "/home/public/scripts/optimizedb", "hour": 1, "day": 5, "date": 13}
			]
		},
		{"sname": "sampleadjunct",
		"username": "sample_sampleadjunct",
		"cname": "sampleadjunct.nfshost.com",
		"status": 0,
		"adjunct": true,
		"sponsor": "member2",
		"sshHostname": "ssh.phx.nearlyfreespeech.net",
		"ftpHostname": "ftp.phx.nearlyfreespeech.net",
		"sshAccess": true,
		"ftpAccess": false,
		"aliases": ["sampleadjunct.nfshost.com"]
		}],
	"domains": [
		{"name": "sample.com",
		"account": "AD20-8675309",
		"expiration": 1656892800,
		"deletion": 1656892800,
		"renewal": 0,
		"status": 1,
		"lock": true,
		"dns": true,
		"forwards": {"enabled": false},
		"privacy": {"enabled": false},
		"nameservers": ["ns.phx1.nearlyfreespeech.net","ns.phx2.nearlyfreespeech.net"],
		"registrant": {
			"company": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
			"phone": "2027737433",
			"fax": ""
			},
		"adminContact": {
			"company": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
			"phone": "2027737433",
			"fax": ""
			},
		"techContact": {
			"company": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
			"phone": "2027737433",
			"fax": ""
			},
		"billContact": {
			"company": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
			"phone": "2027737433",
			"fax": ""
			}
		},
		{"name": "samp.le",
		"account": "0541-CA1CBADD",
		"expiration": 1976230924,
		"deletion": 1976230924,
		"renewal": 0,
		"status": 1,
		"lock": true,
		"dns": false,
		"forwards": {
			"enabled": true,
			"sample": "sample@sample.com",
			"iam": "personal@sample.com"
			},
		"nameservers": ["ns1.somednsho.st","ns2.somednsho.st"],
		"privacy": {
			"enabled": true,
			"expiry": 1976230924,
			"prepaid": false
			},
		"registrant": {
			"company": "samp.le Domain Administrator",
			"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
			"address": "PO BOX 484 COCOA, FL 32923-0484 US",
			"phone": "1.8664570078",
			"fax": "1.8663909061"
			},
		"adminContact": {
			"company": "samp.le Domain Administrator",
			"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
			"address": "PO BOX 484 COCOA, FL 32923-0484 US",
			"phone": "1.8664570078",
			"fax": "1.8663909061"
			},
		"techContact": {
			"company": "samp.le Domain Administrator",
			"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
			"address": "PO BOX 484 COCOA, FL 32923-0484 US",
			"phone": "1.8664570078",
			"fax": "1.8663909061"
			},
		"billContact": {
			"company": "samp.le Domain Administrator",
			"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
			"address": "PO BOX 484 COCOA, FL 32923-0484 US",
			"phone": "1.8664570078",
			"fax": "1.8663909061"
			}
		}],
	"dns": [
		{"name": "sample.com",
		"account": "AD20-8675309",
		"bareDomain": false,
		"enabled": true,
		"spf": false,
		"records": [
			{"id": 10000, "name": "", "type": "MX", "data": "1 ASPMX.L.GOOGLE.COM."},
			{"id": 10001, "name": "", "type": "MX", "data": "5 ALT1.ASPMX.L.GOOGLE.COM."},
			{"id": 10002, "name": "", "type": "MX", "data": "10 ASPMX2.GOOGLEMAIL.COM."},
			{"id": 10003, "name": "static", "type": "CNAME", "data": "static.sample.com.s3.amazonaws.com."},
			{"id": 10004, "name": "www", "type": "CNAME", "data": "sample.nfshost.com."}
			]
		}],
	"databases": [
		{"name": "sampledb",
		"account": "AD20-8675309",
		"autorestartable": true,
		"runnable": true,
		"running": true,
		"node": "m8",
		"type": "MySQL 5.0",
		"size": 3260416
		}],
	"openSupport": [{
		"ticket": 123456,
		"status": "In Queue",
		"subject": "Restore from backup",
		"messages": [
			{"time": 1346529600, "from": "Sample User", "message": "My blog got hacked yesterday and I need to restore it from my backups"},
			{"time": 1346537700, "from": "Tech Support", "message": "Your site has been restored with backups taken on 8/25."}
			]
		}],
	"closedSupport": [{
		"ticket": 112358,
		"status": "Pending Auto-Close",
		"subject": "Request an API key",
		"messages": [
			{"time": 1345115700, "from": "Sample User", "message": "I am working on a NFS client and would like my API key"},
			{"time": 1345122900, "from": "Tech Support", "message": "Here you go: BADDBEEFDEADD00D"}
			]
		}]
}

Get basic information about a membership and affiliated accounts, sites, domains and databases
GET /member/basic
< 200
< Content-Type: application/json
{
	"login": "sample",
	"name": "Sample User",
	"email": "sample@sample.com",
	"status": "OK",
	"supportPoints": 10,
	"globalSSH": true,
	"globalFTP": false,
	"shell": 0,
	"accounts": ["AD20-8675309","0541-CA1CBADD"],
	"sites": ["samplesite","samplesite2","samplesite3", "sampleadjunct"],
	"domains": ["sample.com","samp.le"],
	"dns": ["sample.com"],
	"databases": ["sampledb"],
	"openSupport": [123456],
	"closedSupport": [112358]
	"sessions": [
		{"start": 1344189552, "duration": 3600, "address": "127.0.0.1", "agent": "Mozilla/5.0 AppleWebKit/535.19 Ubuntu/12.04 Chrome/18.0.1025.168"}
		],
	"keys": [
		{"type": "RSA", "length": 4096, "fingerprint": "01:02:03:04:05:06:07:08:09:0A:0B:0C:0D:0E:0F:10", "comment": "Website Key (sample@sample.com)", "options": ""}
		]
}

Update the member's shell choice or global FTP status
PUT /member
> Content-Type: application/json
{
	"shell": 2,
	"globalFTP": true
}
< 205


Update the member's email address
PUT /member
> Content-Type: application/json
{
	"email": sample@sam.pl
}
< 202
< Content-Type: application/json
{
	"message": "A confirmation email has been sent to complete update."
}

--
Account Endpoints
This section relates to all endpoints in regard to a member's accounts
--
Create a new account for a member
POST /accounts
> Content-Type: application/json
{
	"fname": "Sample",
	"lname": "User",
	"oname": "",
	"sname": "business",
	"address": "1600 Pennsylvania Ave",
	"city": "Washington, D.C.",
	"state": "",
	"postal": "20204",
	"country": "US",
	"phone": "2027737433"
}
< 201
< Content-Location: https://api.nearlyfreespeech.net/v2/accounts/AD20-8675309
< Content-Type: application/json
{
	"name": "AD20-8675309",
	"sname": "business",
	"number": "AD20-8675309",
	"status": "OK",
	"xferTotal": 0,
	"warnings": [500,100],
	"balance": 2,
	"xferRate": 10737418,
	"xferUnbilled": 0,
	"storageUnbilled": 0,
	"created": 1041480306,
	"charged": 1041480306,
	"modified": 1041480306,
	"contact": {
		"oname": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave",
		"city": "Washington, D.C.",
		"state": "",
		"postal": "20204",
		"country": "US",
		"phone": "2027737433",
		"emergency": "sample@sample.com"
		},
	"activity": {"current": [],"recurring": []}
}

Transfer funds between a member's accounts
POST /accounts/transfers
> Content-Type: application/json
{
	"from": "AD20-8675309",
	"to": "0541-CA1CBADD",
	"amount": 1000
}
< 205


Deposit funds into a member's account
POST /accounts/deposits
> Content-Type: application/json
{
	"method": 0,
	"account": "0541-CA1CBADD",
	"amount": 1500,
	"cardInfo": {
		"cardnumber": "4747256077959177",
		"cvv": "302",
		"expiry": "1220",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave",
		"city": "Washington, D.C.",
		"state": "",
		"postal": "20204",
		"country": "US"
		}
}
< 200
< Content-Type: application/json
{
	"grossDeposit": 1500,
	"fee": 150,
	"rebate": 65,
	"netDeposit": 1415,
	"balance": 2134
}

Get the list of accounts attached to a membership
GET /accounts
< 200
< Content-Type: application/json
{
	"AD20-8675309": {
		"sname": "business",
		"number": "AD20-8675309",
		"status": "OK",
		"xferTotal": 237060719903,
		"warnings": [500,100],
		"balance": 1420,
		"xferRate": 16242304,
		"xferUnbilled": 22597911,
		"storageUnbilled": 18967354,
		"created": 1041480306,
		"charged": 1344180247,
		"modified": 1344180247,
		"contact": {
			"oname": "Sample Corp",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave",
			"city": "Washington, D.C.",
			"state": "",
			"postal": "20204",
			"country": "US",
			"phone": "2027737433",
			"emergency": "sample@sample.com"
			},
		"activity": {
			"current": [
				{"name": "samplesite Site Charge", "charge": 1, "note": ""},
				{"name": "sampledb MySQL Charge", "charge": 2, "note": ""},
				{"name": "Storage Charge", "charge": 30, "note": ""}
				],
			"recurring": [
				{"name": "Dynamic Sites", "charge": 1, "note": "1 site"},
				{"name": "DNS", "charge": 0.111, "note": "1 zone, 1 registered & hosted"},
				{"name": "MySQL", "charge": 2, "note": "1 process"},
				{"name": "RespectMyPrivacy", "charge": 0, "note": "1 private domain, 1 prepaid"}
				]
			}
		},
	"0541-CA1CBADD": {
		"sname": "personal",
		"number": "0541-CA1CBADD",
		"status": "OK",
		"xferTotal": 23697482056,
		"warnings": [500,100],
		"balance": 719,
		"xferRate": 13729026,
		"xferUnbilled": 22597911,
		"storageUnbilled": 18967354,
		"created": 1144198923,
		"charged": 1344564246,
		"modified": 1344564246,
		"contact": {
			"oname": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave",
			"city": "Washington, D.C.",
			"state": "",
			"postal": "20204",
			"country": "US",
			"phone": "2027737433",
			"emergency": "sample@samp.le"
			},
		"activity": {
			"current": [
				{"name": "samplesite2 Site Charge", "charge": 1,"note": ""},
				{"name": "samplesite3 Site Charge", "charge": 1,"note": ""},
				{"name": "Storage Charge", "charge": 30, "note": ""}
				],
			"recurring": [
				{"name": "Dynamic Sites", "charge": 2, "note": "2 sites"},
				{"name": "DNS", "charge": 0.111, "note": "1 zone, 1 registered & hosted"},
				{"name": "RespectMyPrivacy", "charge": 0, "note": "1 private domain, 1 prepaid"}
				]
			}
		}
}

Get a storage summary regarding all sites attached to a specific account
GET /accounts/0541-CA1CBADD/storage
< 200
< Content-Type: application/json
{
	"samplesite2": 134850810,
	"samplesite3": 78418944,
	"total": 213269754
}

Get a bandwidth summary regarding all sites attached to a specific account
GET /accounts/AD20-8675309/bandwidth/5
< 200
< Content-Type: application/json
{
	"image": "http://api.nearlyfreespeech.net/v2/pictures/picture.png",
	"1342396799": {
			"samplesite": 6467166,
			"total": 6467166
			},
	"1343001599": {
			"samplesite": 6333859,
			"total": 6333859
			},
	"1342396799": {
			"samplesite": 6467166,
			"total": 6467166
			},
	"1343001599": {
			"samplesite": 6333859,
			"total": 6333859
			},
	"1343606399": {
			"samplesite": 4095185,
			"total": 4095185
			},
	"1344211199": {
			"samplesite": 4095185,
			"total": 4095185
			},
	"1344211199": {
			"samplesite": 1858923,
			"total": 1858923
			},
	"total": 18755133
}

Get all information regarding a specified account
GET /accounts/AD20-8675309
< 200
< Content-Type: application/json
{
	"sname": "business",
	"number": "AD20-8675309",
	"status": "OK",
	"xferTotal": 237060719903,
	"warnings": [500,100],
	"balance": 1420,
	"xferRate": 16242304,
	"xferUnbilled": 22597911,
	"storageUnbilled": 18967354,
	"created": 1041480306,
	"charged": 1344180247,
	"modified": 1344180247,
	"contact": {
		"oname": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave",
		"city": "Washington, D.C.",
		"state": "",
		"postal": "20204",
		"country": "US",
		"phone": "2027737433",
		"emergency": "sample@sample.com"
		},
	"activity": {
		"current": [
			{"name": "samplesite Site Charge", "charge": 1, "note": ""},
			{"name": "sample.db MySQL Charge", "charge": 2, "note": ""},
			{"name": "Storage Charge", "charge": 30, "note": ""}
			],
		"recurring": [
			{"name": "Dynamic Sites", "charge": 1, "note": "1 site"},
			{"name": "DNS", "charge": 0.111, "note": "1 zone, 1 registered & hosted"},
			{"name": "MySQL", "charge": 2, "note": "1 process"},
			{"name": "RespectMyPrivacy", "charge": 0, "note": "1 private domain, 1 prepaid"}
			]
		}
}

Get the most volatile information about the account
GET /accounts/AD20-8675309/basic
< 200
< Content-Type: application/json
{
	"balance": 1420,
	"status": "OK",
	"xferTotal": 237060719903,
	"xferRate": 16242304,
	"charged": 1344180247,
	"modified": 1344180247,
}

Modify shortname, balance warnings and contact information for an account
PUT /accounts/AD20-8675309
> Content-Type: application/json
{
	"sname": "work",
	"warnings": [500,1100],
	"contact": {
		"name": "Example User",
		"address": "1600 Pennsylvania Ave",
		"city": "Washington, D.C.",
		"state": "",
		"zip": "20204",
		"country": "US",
		"phone": "2027737433",
		"emergency": "iam@sample.com"
		}
}
< 205


Delete an account
DELETE /accounts/AD20-8675309
< 205


--
Site Endpoints
This section relates to all endpoints in regard to a member's sites
--
Create a new site
POST /sites
> Content-Type: application/json
{
	"sname": "samplesite4",
	"account": "AD20-8675309",
	"auth": "0102030405060708"
}
< 201
< Content-Location: http://api.nearlyfreespeech.net/v2/sites/samplesite4
< Content-Type: application/json
{
	"sname": "samplesite4",
	"username": "sample_samplesite4",
	"maintenance": false,
	"adjunct": false,
	"cname": "samplesite.nfshost.com",
	"ctype": 0,
	"type": 5,
	"root": "/f3/samplesite4/",
	"cluster": "coh-1-228",
	"realm": 2,
	"enabled": true,
	"control": ["Allow All"],
	"admin": "nobody",
	"bank": 100,
	"account": "AD20-8675309",
	"sshHostname": "ssh.phx.nearlyfreespeech.net",
	"ftpHostname": "ftp.phx.nearlyfreespeech.net",
	"sshAccess": true,
	"ftpAccess": false,
	"alog": false,
	"elog": false,
	"rlog": 0,
	"rotation": 0,
	"compression": 0,
	"created": 1139040612,
	"xferUnbilled": 0,
	"storageUnbilled": 0,
	"repSize": 0,
	"lbackup": 1139040612,
	"rbackup": 0,
	"totalRAU": 0,
	"avgRAU": 0,
	"addresses": ["37.38.39.40","41.42.43.44","45.46.47.48"],
	"ipv6": false,
	"bandwidth": 0,
	"adjuncts": [],
	"aliases": ["samplesite4.nfshost.com"],
	"tasks": []
}

Get the list of sites attached to a membership
GET /sites
< 200
< Content-Type: application/json
{
	"samplesite": {
		"sname": "samplesite",
		"username": "sample_samplesite",
		"maintenance": false,
		"adjunct": false,
		"cname": "www.sample.com",
		"ctype": 2,
		"type": 5,
		"root": "/f2/samplesite/",
		"cluster": "coh-1-225",
		"realm": 2,
		"enabled": true,
		"control": ["Allow All"],
		"admin": "nobody",
		"bank": 100,
		"account": "AD20-8675309",
		"sshHostname": "ssh.phx.nearlyfreespeech.net",
		"ftpHostname": "ftp.phx.nearlyfreespeech.net",
		"sshAccess": true,
		"ftpAccess": false,
		"alog": false,
		"elog": false,
		"rlog": 0,
		"rotation": 0,
		"compression": 0,
		"created": 1139040612,
		"xferUnbilled": 13524972,
		"storageUnbilled": 26163811,
		"repSize": 78418944,
		"lbackup": 1344197191,
		"rbackup": 1344197191,
		"totalRAU": 109.893,
		"avgRAU": 12.206,
		"addresses": ["1.2.3.4","5.6.7.8","9.10.11.12"],
		"ipv6": false,
		"bandwidth": 0,
		"adjuncts": ["member1","member2"],
		"aliases": ["www.sample.com","samplesite.nfshost.com"],
		"tasks": [
			{"tag": "permissions", "command": "chmod -R ug+rwx /home/public/blog", "user": 1, "hour": 7, "day": -1, "date": -1}
			]
		},
	"samplesite2": {
		"sname": "samplesite2",
		"username": "sample_samplesite2",
		"maintenance": false,
		"adjunct": false,
		"cname": "www.examp.le",
		"ctype": 1,
		"type": 5,
		"root": "/f5/samplesite2/",
		"cluster": "coh-1-226",
		"realm": 2,
		"enabled": true,
		"control": ["Allow All"],
		"admin": "nobody",
		"bank": 52,
		"account": "0541-CA1CBADD",
		"sshHostname": "ssh.phx.nearlyfreespeech.net",
		"ftpHostname": "ftp.phx.nearlyfreespeech.net",
		"sshAccess": true,
		"ftpAccess": false,
		"alog": false,
		"elog": false,
		"rlog": 0,
		"rotation": 0,
		"compression": 0,
		"created": 1310173385,
		"xferUnbilled": 13524972,
		"storageUnbilled": 26163811,
		"repSize": 134850810,
		"lbackup": 1344197191,
		"rbackup": 0,
		"totalRAU": 17.747,
		"avgRAU": 3.095,
		"addresses": ["13.14.15.16","17.18.19.20","21.22.23.24"],
		"ipv6": false,
		"bandwidth": 0,
		"adjuncts": [],
		"aliases": ["www.examp.le","samplesite2.nfshost.com"],
		"tasks": []
		},
	"samplesite3": {
		"sname": "samplesite3",
		"username": "sample_samplesite3",
		"maintenance": false,
		"adjunct": false,
		"cname": "samplesite3.nfshost.com",
		"ctype": 0,
		"type": 5,
		"root": "/f1/samplesite3/",
		"cluster": "coh-1-227",
		"realm": 2,
		"enabled": false,
		"control": ["Allow All"],
		"admin": "nobody",
		"bank": 96,
		"account": "0541-CA1CBADD",
		"sshHostname": "ssh.phx.nearlyfreespeech.net",
		"ftpHostname": "ftp.phx.nearlyfreespeech.net",
		"sshAccess": true,
		"ftpAccess": false,
		"alog": false,
		"elog": false,
		"rlog": 0,
		"rotation": 0,
		"compression": 0,
		"created": 1310173385,
		"xferUnbilled": 13524972,
		"storageUnbilled": 26163811,
		"repSize": 78418944,
		"lbackup": 1344197191,
		"rbackup": 0,
		"totalRAU": 202.112,
		"avgRAU": 18.586,
		"addresses": ["25.26.27.28","29.30.31.32","33.34.35.36","2e80::ff09:1123"],
		"ipv6": true,
		"bandwidth": 0,
		"adjuncts": ["member1","member3"],
		"aliases": ["samplesite3.nfshost.com"],
		"tasks": [
			{"tag": "logstuff", "command": "/home/private/dologstuff", "hour": 3, "day": -1, "date": 31},
			{"tag": "optimizedb", "command": "/home/public/scripts/optimizedb", "hour": 1, "day": 5, "date": 13}
			]
		}
}

Get all information regarding a site
GET /sites/samplesite
< 200
< Content-Type: application/json
{
	"sname": "samplesite",
	"username": "sample_samplesite",
	"maintenance": false,
	"adjunct": false,
	"cname": "www.sample.com",
	"ctype": 2,
	"type": 5,
	"root": "/f2/samplesite/",
	"cluster": "coh-1-225",
	"realm": 2,
	"enabled": true,
	"control": ["Allow All"],
	"admin": "nobody",
	"bank": 100,
	"account": "AD20-8675309",
	"sshHostname": "ssh.phx.nearlyfreespeech.net",
	"ftpHostname": "ftp.phx.nearlyfreespeech.net",
	"sshAccess": true,
	"ftpAccess": false,
	"alog": false,
	"elog": false,
	"rlog": 0,
	"rotation": 0,
	"compression": 0,
	"created": 1139040612,
	"xferUnbilled": 13524972,
	"storageUnbilled": 26163811,
	"repSize": 78418944,
	"lbackup": 1344197191,
	"rbackup": 1344197191,
	"totalRAU": 109.893,
	"avgRAU": 12.206,
	"addresses": ["1.2.3.4","5.6.7.8","9.10.11.12"],
	"ipv6": false,
	"bandwidth": 0,
	"adjuncts": ["member1","member2"],
	"aliases": ["www.sample.com","samplesite.nfshost.com"],
	"tasks": [
		{"tag": "permissions", "command": "chmod -R ug+rwx /home/public/blog", "user": 1, "hour": 7, "day": -1, "date": -1}
		]
}

Return the most volatile information regarding a site
GET /sites/samplesite/basic
< 200
< Content-Type: application/json
{
	"enabled": true,
	"bank": 100,
	"xferUnbilled": 13524972,
	"storageUnbilled": 26163811,
	"repSize": 78418944,
	"lbackup": 1344197191,
	"rbackup": 1344197191,
	"addresses": ["1.2.3.4","5.6.7.8","9.10.11.12"]
}

Return storage activity for the desired report period
GET /sites/samplesite/storage/0
< 200
< Content-Type: application/json
{
	"image": "http://api.nearlyfreespeech.net/v2/pictures/picture.png",
	"activity": [
		{"time": 1343087999, "start": 78418944, "end": 78418944, "avg": 78418944},
		{"time": 1343174399, "start": 78418944, "end": 78418944, "avg": 78418944},
		{"time": 1343260799, "start": 78418944, "end": 78418944, "avg": 78418944},
		{"time": 1343347199, "start": 78418944, "end": 78418944, "avg": 78418944},
		{"time": 1343433599, "start": 78418944, "end": 78418944, "avg": 78418944},
		{"time": 1343519999, "start": 78418944, "end": 78418944, "avg": 78418944},
		{"time": 1343606399, "start": 78418944, "end": 78418944, "avg": 78418944}
		]
}

Return bandwidth activity for the desired report period
GET /sites/samplesite/bandwidth/0
< 200
< Content-Type: application/json
{
	"image": "http://api.nearlyfreespeech.net/v2/pictures/picture.png",
	"activity": [
		{"time": 1343606399, "amount": 306181},
		{"time": 1343692799, "amount": 243273},
		{"time": 1343779199, "amount": 566781},
		{"time": 1343865599, "amount": 123337},
		{"time": 1343951999, "amount": 462056},
		{"time": 1344038399, "amount": 181972},
		{"time": 1344124799, "amount": 114030},
		{"time": 1344211199, "amount": 887285}
		]
}

Update the canonical name and type, logging options, type, realm or status for a site
PUT /sites/samplesite
> Content-Type: application/json
{
	"cname": "samplesite.nfshost.com",
	"ctype": 0,
	"alog": false,
	"elog": true,
	"rlog": 2,
	"rotation": 2,
	"compression": 2,
	"type": 0,
	"realm": 3,
	"enabled": false
}
< 205


Add alias for a site
POST /sites/samplesite/aliases
> Content-Type: application/json
{
	"alias": "www.example.net"
}
< 205


Add adjunct member for a site
POST /sites/samplesite/adjuncts
> Content-Type: application/json
{
	"adjunct": "member3"
}

Remove alias for a site
DELETE /sites/samplesite/aliases/www.example.net
< 205


Remove adjunct member for a site
DELETE /sites/samplesite/adjuncts/member3
<205


Remove a site
DELETE /sites/samplesite
< 205


--
Domain Endpoints
This section relates to all endpoints in regard to a member's domains
--
Register a new domain
POST /domains
> Content-Type: application/json
{
	"name": "sample",
	"tld": 1,
	"account": "0541-CA1CBADD",
	"term": 2,
	"dns": true,
	"privacy": 0,
	"renewal": 0
}
< 201
< Content-Location: https://api.nearlyfreespeech.net/v2/domains/sample.net
< Content-Type: application/json
{
	"name": "sample.net"
	"account": "0541-CA1CBADD",
	"expiration": 1656892800,
	"deletion": 1656892800,
	"renewal": 0,
	"status": 1,
	"lock": false,
	"dns": true,
	"nameservers": ["ns1.phx.nearlyfreespeech.net","ns2.phx.nearlyfreespeech.net"],
	"forwards": {"enabled": false},
	"privacy": {"enabled": false},
	"registrant": {
		"company": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
		"phone": "2027737433",
		"fax": ""
		},
	"adminContact": {
		"company": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
		"phone": "2027737433",
		"fax": ""
		},
	"techContact": {
		"company": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
		"phone": "2027737433",
		"fax": ""
		},
	"billContact": {
		"company": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
		"phone": "2027737433",
		"fax": ""
		}
}

Initiate a domain transfer into NearlyFreeSpeech.Net
POST /domains/transfers
> Content-Type: application/json
{
	"domain": "sample",
	"tld": 2,
	"account": "AD20-8675309",
	"privacy": 1
}
< 202
< Content-Type: application/json
{
	"message": "Transfer initiated"
}

Renew domain
POST /domains/renewals
> Content-Type: application/json
{
	"domain": "sample",
	"tld": 0,
	"term": 2,
	"account": "AD20-8675309",
	"privacy": 2
}
< 200
< Content-Type: application/json
{
	"account": "AD20-8675309",
	"expiration": 1720051200,
	"deletion": 1720051200,
	"renewal": 0,
	"status": 1,
	"lock": false,
	"dns": true,
	"forwards": {"enabled": false},
	"privacy": {
		"enabled": true,
		"prepaid": true
		},
	"nameservers": ["ns.phx1.nearlyfreespeech.net","ns.phx2.nearlyfreespeech.net"],
	"registrant": {
		"company": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
		"phone": "2027737433",
		"fax": ""
		},
	"adminContact": {
		"company": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
		"phone": "2027737433",
		"fax": ""
		},
	"techContact": {
		"company": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
		"phone": "2027737433",
		"fax": ""
		},
	"billContact": {
		"company": "",
		"name": "Sample User",
		"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
		"phone": "2027737433",
		"fax": ""
		}
}


Get a list of all domains under the member's control
GET /domains
< 200
< Content-Type: application/json
{
	"sample.com": {
		"name": "sample.com",
		"account": "AD20-8675309",
		"expiration": 1656892800,
		"deletion": 1656892800,
		"renewal": 0,
		"status": 1,
		"lock": true,
		"dns": true,
		"forwards": {"enabled": false},
		"privacy": {"enabled": false},
		"nameservers": ["ns.phx1.nearlyfreespeech.net","ns.phx2.nearlyfreespeech.net"],
		"registrant": {
			"company": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
			"phone": "2027737433",
			"fax": ""
			},
		"adminContact": {
			"company": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
			"phone": "2027737433",
			"fax": ""
			},
		"techContact": {
			"company": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
			"phone": "2027737433",
			"fax": ""
			},
		"billContact": {
			"company": "",
			"name": "Sample User",
			"address": "1600 Pennsylvania Ave Washington, D.C. 20204 US",
			"phone": "2027737433",
			"fax": ""
			}
		},
	"samp.le": {
		"name": "samp.le",
		"account": "0541-CA1CBADD",
		"expiration": 1976230924,
		"deletion": 1976230924,
		"renewal": 0,
		"status": 1,
		"lock": true,
		"dns": false,
		"forwards": {
			"enabled": true,
			"sample": "sample@sample.com",
			"iam": "personal@sample.com"
			},
		"nameservers": ["ns1.somednsho.st","ns2.somednsho.st"],
		"privacy": {
			"enabled": true,
			"expiry": 1976230924
			"prepaid": false
			},
		"registrant": {
			"company": "sample.com Domain Administrator",
			"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
			"address": "PO BOX 484 COCOA, FL 32923-0484 US",
			"phone": "1.8664570078",
			"fax": "1.8663909061"
			},
		"adminContact": {
			"company": "sample.com Domain Administrator",
			"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
			"address": "PO BOX 484 COCOA, FL 32923-0484 US",
			"phone": "1.8664570078",
			"fax": "1.8663909061",
			},
		"techContact": {
			"company": "sample.com Domain Administrator",
			"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
			"address": "PO BOX 484 COCOA, FL 32923-0484 US",
			"phone": "1.8664570078",
			"fax": "1.8663909061"
			},
		"billContact": {
			"company": "sample.com Domain Administrator",
			"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
			"address": "PO BOX 484 COCOA, FL 32923-0484 US",
			"phone": "1.8664570078",
			"fax": "1.8663909061"
			}
		}
}

Get all information regarding a specific domain
GET /domains/samp.le
< 200
< Content-Type: application/json
{
	"name": "samp.le",
	"account": "0541-CA1CBADD",
	"expiration": 1976230924,
	"deletion": 1976230924,
	"renewal": 0,
	"status": 1,
	"lock": false,
	"dns": false,
	"forwards": {
		"enabled": true,
		"sample": "sample@sample.com",
		"iam": "personal@sample.com"
		},
	"nameservers": ["ns1.somednsho.st","ns2.somednsho.st"],
	"privacy": {
		"enabled": true,
		"expiry": 1976230924
		"prepaid": false
		},
	"registrant": {
		"company": "sample.com Domain Administrator",
		"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
		"address": "PO BOX 484 COCOA, FL 32923-0484 US",
		"phone": "1.8664570078",
		"fax": "1.8663909061"
		},
	"adminContact": {
		"company": "sample.com Domain Administrator",
		"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
		"address": "PO BOX 484 COCOA, FL 32923-0484 US",
		"phone": "1.8664570078",
		"fax": "1.8663909061",
		},
	"techContact": {
		"company": "sample.com Domain Administrator",
		"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
		"address": "PO BOX 484 COCOA, FL 32923-0484 US",
		"phone": "1.8664570078",
		"fax": "1.8663909061"
		},
	"billContact": {
		"company": "sample.com Domain Administrator",
		"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
		"address": "PO BOX 484 COCOA, FL 32923-0484 US",
		"phone": "1.8664570078",
		"fax": "1.8663909061"
		}
}

Return domain's transfer code
GET /domains/sample.com/xferCode
< 200
< Content-Type: application/json
{
	"code": 1337
}

Modify status of domain lock, renewal type, nameservers, privacy or attached account
PUT /domains/sample.com
> Content-Type: application/json
{
	"lock": false,
	"privacy": 2,
	"nameservers": ["ns.phx3.nearlyfreespeech.net","ns.phx4.nearlyfreespeech.net"],
	"account": "0541-CA1CBADD"
}
< 200
< Content-Type: application/json
{
	"name": "sample.com",
	"account": "AD20-8675309",
	"expiration": 1656892800,
	"deletion": 1656892800,
	"renewal": 0,
	"status": 1,
	"lock": true,
	"dns": true,
	"forwards": {"enabled": false},
	"privacy": {
		"enabled": true,
		"prepaid": true
		"expiry": 1656892800
		},
	"nameservers": ["ns.phx1.nearlyfreespeech.net","ns.phx2.nearlyfreespeech.net"],
	"registrant": {
		"company": "sample.com Domain Administrator",
		"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
		"address": "PO BOX 484 COCOA, FL 32923-0484 US",
		"phone": "1.8664570078",
		"fax": "1.8663909061"
		},
	"adminContact": {
		"company": "sample.com Domain Administrator",
		"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
		"address": "PO BOX 484 COCOA, FL 32923-0484 US",
		"phone": "1.8664570078",
		"fax": "1.8663909061",
		},
	"techContact": {
		"company": "sample.com Domain Administrator",
		"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
		"address": "PO BOX 484 COCOA, FL 32923-0484 US",
		"phone": "1.8664570078",
		"fax": "1.8663909061"
		},
	"billContact": {
		"company": "sample.com Domain Administrator",
		"name": "c/o RespectMyPrivacy, LLC (sample.com@RespectMyPrivacy.COM)",
		"address": "PO BOX 484 COCOA, FL 32923-0484 US",
		"phone": "1.8664570078",
		"fax": "1.8663909061"
		}
}

--
DNS Endpoints
This section relates to all endpoints in regard to a member's domain's DNS
--
Add NFS.N DNS for a domain
POST /dns
> Content-Type: application/json
{
	"domain": "examp.le",
	"account": "0541-CA1CBADD",
	"records": [
		{"name": "www", "type": "CNAME", "data": "sample2.nfshost.com"},
		{"name": "proxy", "type": "A", "data": "1.2.4.8"},
		{"name": "server", "type": "AAAA", "data": "2000:3000:4000::5678"},
		{"name": "www2", "type": "NS", "data": "16.32.64.128"},
		{"name": "", "type": "TXT", "data": "Oh how did I get here I am not good with computer"}
		]
}
< 201
< Content-Location: https://api.nearlyfreespeech.net/dns/examp.le
< Content-Type: application/json
{
	"name": "examp.le",
	"account": "0541-CA1CBADD",
	"enabled": true,
	"bareDomain": false,
	"spf": false,
	"records": [
		{"id": 11001, "name": "www", "type": "CNAME", "data": "sample2.nfshost.com"},
		{"id": 11002, "name": "proxy", "type": "A", "data": "1.2.4.8"},
		{"id": 11003, "name": "server", "type": "AAAA", "data": "2000:3000:4000::5678"},
		{"id": 11004, "name": "www2", "type": "NS", "data": "16.32.64.128"},
		{"id": 11005, "name": "", "type": "TXT", "data": "Oh how did I get here I am not good with computer"}
		]
}

List all a member's domains that use NFS.N DNS
GET /dns
< 200
< Content-Type: application/json
{
	"sample.com": {
		"account": "AD20-8675309",
		"bareDomain": false,
		"enabled": true,
		"spf": false,
		"records": [
			{"id": 10000, "name": "", "type": "MX", "data": "1 ASPMX.L.GOOGLE.COM."},
			{"id": 10001, "name": "", "type": "MX", "data": "5 ALT1.ASPMX.L.GOOGLE.COM."},
			{"id": 10002, "name": "", "type": "MX", "data": "10 ASPMX2.GOOGLEMAIL.COM."},
			{"id": 10003, "name": "static", "type": "CNAME", "data": "static.sample.com.s3.amazonaws.com."},
			{"id": 10004, "name": "www", "type": "CNAME", "data": "sample.nfshost.com."}
			]
		}
}

List NFS.N DNS information for a specific domain
GET /dns/sample.com
< 200
< Content-Type: application/json
{
	"account": "AD20-8675309",
	"bareDomain": false,
	"enabled": true,
	"spf": false,
	"records": [
		{"id": 10000, "name": "", "type": "MX", "data": "1 ASPMX.L.GOOGLE.COM."},
		{"id": 10001, "name": "", "type": "MX", "data": "5 ALT1.ASPMX.L.GOOGLE.COM."},
		{"id": 10002, "name": "", "type": "MX", "data": "10 ASPMX2.GOOGLEMAIL.COM."},
		{"id": 10003, "name": "static", "type": "CNAME", "data": "static.sample.com.s3.amazonaws.com."},
		{"id": 10004, "name": "www", "type": "CNAME", "data": "sample.nfshost.com."}
		]
}

Enable/Disable DNS service, SPF protection or bare domain forwarding for a domain
PUT /dns/sample.com
> Content-Type: application/json
{
	"enabled": false,
	"spf": true,
	"bareDomain": true
}
< 205


Add new resource record for a domain
POST /dns/sample.com/records
> Content-Type: application/json
{
	"name": "",
	"type": "TXT",
	"data": "v=spf1 -all"
}
< 201
< Location: http://api.nearlyfreespeech.net/v2/dns/sample.com/records/10002


Remove resource record for a domain
DELETE /dns/sample.com/records/10002
< 205


Remove NFS.N DNS for a domain
DELETE /dns/sample.com
< 205


--
Database Endpoints
This section relates to all endpoints in regard to a member's databases
--
Create a new database process
POST /db
> Content-Type: application/json
{
	"name": "sampledb2",
	"account": "AD20-8675309"
}
< 201
< Content-Location: https://api.nearlyfreespeech.net/db/sampledb2
< Content-Type: application/json
{
	"name": "sampledb2",
	"account": "AD20-8675309",
	"autorestartable": true,
	"runnable": true,
	"running": true,
	"node": "m8",
	"type": "MariaDB 5.3",
	"size": 10240
}

Get a list of all database processes owned by the member
GET /db
< 200
< Content-Type: application/json
{
	"sampledb": {
		"account": "AD20-8675309",
		"autorestartable": true,
		"runnable": true,
		"running": true,
		"node": "m8",
		"type": "MySQL 5.0",
		"size": 3260416
		}
}

Get all information regarding a database process
GET /db/sampledb
< 200
< Content-Type: application/json
{
	"name": "sampledb",
	"account": "AD20-8675309",
	"autorestartable": true,
	"runnable": true,
	"running": true,
	"node": "m8",
	"type": "MySQL 5.0",
	"size": 3260416
}

Create a new database
POST /db/sampledb
> Content-Type: application/json
{
	"database": "example",
	"user": "sample",
	"password": "pigeonbiscuits"
}
< 201
< Content-Type: application/json
{
	"message": "Database successfully created"
}

Remove a database process
DELETE /db/sample
< 205


--
Support Endpoints
This section relates to filing and viewing support requests, both paid and free.
--

File a support request
POST /support
> Content-Type: application/json
{
	"type": 0,
	"urgent": false,
	"subject": "Restore from backup",
	"body": "My blog got hacked yesterday and I need to restore it from my backups"
}
< 201
< Content-Type: application/json
< Content-Location: https://api.nearlyfreespeech.net/v2/support/123456
{
	"ticket": 123456,
	"status": "Available",
	"subject": "Restore from backup",
	"messages": [
		{"time": 1346529600, "from": "Sample User", "message": "My blog got hacked yesterday and I need to restore it from my backups"}
		]
}

Find all open and recently-closed support requests
GET /support
< 200
< Content-Type: application/json
{
	"open": [{
		"ticket": 123456,
		"status": "In Queue",
		"subject": "Restore from backup",
		"messages": [
			{"time": 1346529600, "from": "Sample User", "message": "My blog got hacked yesterday and I need to restore it from my backups"},
			{"time": 1346537700, "from": "Tech Support", "message": "Your site has been restored with backups taken on 8/25."}
			]
		}],
	"closed": [{
		"ticket": 112358,
		"status": "Pending Auto-Close",
		"subject": "Request an API key",
		"messages": [
			{"time": 1345115700, "from": "Sample User", "message": "I am working on a NFS client and would like my API key"},
			{"time": 1345122900, "from": "Tech Support", "message": "Here you go: BADDBEEFDEADD00D"}
			]
		}]
}

Get details of support issue
GET /support/123456
< 200
< Content-Type: application/json
{
	"ticket": 123456,
	"status": "In Queue",
	"subject": "Restore from backup",
	"messages": [
		{"time": 1346529600, "from": "Sample User", "message": "My blog got hacked yesterday and I need to restore it from my backups"},
		{"time": 1346537700, "from": "Tech Support", "message": "Your site has been restored with backups taken on 8/25."}
		]
}

Respond to a support issue that has already been created
POST /support/123456
> Content-Type: application/json
{
	"message": "Thanks :)"
}
< 200
< Content-Type: application/json
{
	"ticket": 123456,
	"status": "Pending Auto-Close",
	"subject": "Restore from backup",
	"messages": [
		{"time": 1346529600, "from": "Sample User", "message": "My blog got hacked yesterday and I need to restore it from my backups"},
		{"time": 1346537700, "from": "Tech Support", "message": "Your site has been restored with backups taken on 8/25."},
		{"time": 1346541300, "from": "Sample User", "message": "Thanks :)"}
		]
}

--
Error Endpoints
This section relates to endpoints that are only used to document possible errors and will not be in production. Error responses will have a standardized layout:

	{
		"error": string
		"message": string
		"reference": string
		"response": object
	}

The "error" value will contain a code to distinguish the error; the "message" value will contain a human-readable description of the error; the "reference" value will contain a link back to relevant documentation and the "response" value will contain more specific errors in validation, if necessary.
--

Error obtained by trying to access an endpoint over HTTP
GET /needTLS
< 426
< Content-Type: application/json
{
	"error": "encryptionRequired",
	"message": "All endpoints must be accessed over HTTPS.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by using an incorrect verb on an endpoint
GET /badVerb
< 405
< Content-Type: application/json
{
	"error": "invalidVerb",
	"message": "Invalid verb on this endpoint.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by trying to access a resource that doesn't exist
GET /noItem
< 404
< Content-Type: application/json
{
	"error": "invalidResource",
	"message": "The resource the previous request is trying to access does not exist.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by trying to request an action that costs money when the associated account does not have enough to cover it
GET /noCash
< 402
< Content-Type: application/json
{
	"error": "insufficientFunds",
	"message": "The account specified to fund this action cannot cover the cost.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by trying to access a resource either before being authorized or with invalid credentials 
(e.g., trying to access another member's resources or just expired credentials)
GET /badAuth
< 401
< Content-Type: application/json
{
	"error": "invalidAuth",
	"message": "Your authorization credentials are invalid.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by not including all required fields necessary for an endpoint
GET /needReqs
< 400
< Content-Type: application/json
{
	"error": "missingReqs",
	"message": "The previous request was missing some required fields necessary for that endpoint.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by including unnecessary fields in a request
GET /uselessFields
< 400
< Content-Type: application/json
{
	"error": "unnecessaryFields",
	"message": "The previous request had fields that were not relevant to the action.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by using an incorrect value in a field (e.g., using a number when a string is expected)
GET /badField
< 400
< Content-Type: application/json
{
	"error": "invalidFields",
	"message": "The previous request had one or more fields where the provided value was an incorrect type.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by not formatting request in strictly valid JSON
GET /badJSON
< 400
< Content-Type: application/json
{
	"error": "invalidJSON",
	"message": "The previous request was not formatted in valid JSON.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by using incorrect encoding with request
GET /badEncoding
< 400
< Content-Type: application/json
{
	"error": "invalidEncoding",
	"message": "The previous request was not encoded in UTF-8.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by responding to a challenge incorrectly
GET /badResponse
< 401
< Content-Type: application/json
{
	"error": "incorrectResponse",
	"message": "The response given does not adequately satisfy the specified challenge.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}

Error obtained by responding to an expired challenge
GET /oldChallenge
< 401
< Content-Type: application/json
{
	"error": "expiredChallenge",
	"message": "The challenge this response is meant to satisfy has expired.",
	"reference": "http://docs.mischif.apiary.io/",
	"response": {}
}
